name: Python Tests

on:
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.5' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          pytest app_test.py -vv
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and deploy on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/simple-cherry-app || git clone https://github.com/JamesLau2001/simple-cherry-app
            cd ~/simple-cherry-app
            git pull
            docker build -t test:latest .
            docker stop test || true
            docker rm test
            docker run -d --name test -p 8080:8080 test:latest
